baseURL = 'https://blog.aermored.com/'
copyright = "2023" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-us'
theme = 'lowkey'
title = 'AERMORed Blog'
enableRobotsTXT = true

# List Config
summaryLength= 15
paginate = 5

[Author]
    name = "AERMORed Team"
    email = "info@aermored.com"

[markup.highlight]
      codeFences = false
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false
